package com.algovis.core;

public enum AlgorithmId {
    BUBBLE_SORT, INSERTION_SORT, SELECTION_SORT, MERGE_SORT, QUICK_SORT, HEAP_SORT,
    BFS, DFS, DIJKSTRA, ASTAR, KRUSKAL, PRIM,
    BST_INSERT, BST_DELETE, TRAVERSALS, AVL_INSERT
}